# SPDX-License-Identifier: MPL-2.0
<#
.SYNOPSIS
    Hosts a dedicated game server on this PC for a playtest.

.DESCRIPTION
    Generated by og-tools New-OgDedicatedServerLauncher. Runs on Windows PowerShell 5.1 and
    PowerShell 7 with no modules. Every value comes from host_server.settings.psd1 next to
    this script.

    Local mode: firewall rule, this-PC and LAN join addresses, start the server, offer to
    start the game. Nothing touches the router or the internet.

    Online mode: firewall rule, UPnP port mapping on the router, public IP lookup and a
    carrier-grade NAT check, internet/this-PC/LAN join addresses, start the server, offer
    to start the game. The UPnP mapping is removed when the script ends or on Ctrl+C.

.PARAMETER Mode
    Local or Online.
#>
param(
    [ValidateSet('Local', 'Online')]
    [string] $Mode = 'Online'
)

function Write-OgHostLine {
    param([string] $Text = '', [string] $Color = '')
    if ($Color) { Write-Host $Text -ForegroundColor $Color }
    else { Write-Host $Text }
}

function Read-OgHostAnswer {
    param([string] $Prompt)
    Read-Host -Prompt $Prompt
}

function Wait-OgHostTick {
    Start-Sleep -Milliseconds 250
}

function Test-OgHostFirewallRule {
    param([string] $RuleName, [string] $Program, [int] $Port)
    $policy = New-Object -ComObject HNetCfg.FwPolicy2
    foreach ($rule in $policy.Rules) {
        if ($rule.Name -eq $RuleName -and $rule.ApplicationName -eq $Program -and $rule.Protocol -eq 17 -and
            [string]$rule.LocalPorts -eq [string]$Port -and $rule.Enabled -and $rule.Direction -eq 1 -and $rule.Action -eq 1) {
            return $true
        }
    }
    $false
}

function Invoke-OgHostElevated {
    param([string] $FilePath, [string] $Arguments)
    $process = Start-Process -FilePath $FilePath -ArgumentList $Arguments -Verb RunAs -WindowStyle Hidden -Wait -PassThru
    $process.ExitCode
}

function New-OgHostNatUpnp {
    New-Object -ComObject HNetCfg.NATUPnP
}

function Get-OgHostUpnpCollection {
    $nat = New-OgHostNatUpnp
    $collection = $nat.StaticPortMappingCollection
    if ($null -eq $collection) { return $null }
    , $collection
}

function Get-OgHostUpnpMapping {
    param($Collection, [int] $Port)
    foreach ($mapping in $Collection) {
        if ($mapping.ExternalPort -eq $Port -and $mapping.Protocol -eq 'UDP') { return $mapping }
    }
    $null
}

function Add-OgHostUpnpMapping {
    param($Collection, [int] $Port, [string] $InternalClient, [string] $Description)
    $Collection.Add($Port, 'UDP', $Port, $InternalClient, $true, $Description)
}

function Remove-OgHostUpnpMapping {
    param($Collection, [int] $Port)
    $Collection.Remove($Port, 'UDP')
}

function Invoke-OgHostHttpGet {
    param([string] $Uri)
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12
    $response = Invoke-WebRequest -Uri $Uri -UseBasicParsing -TimeoutSec 5
    [string]$response.Content
}

function Get-OgHostLanAddresses {
    $result = @()
    foreach ($nic in [System.Net.NetworkInformation.NetworkInterface]::GetAllNetworkInterfaces()) {
        if ($nic.OperationalStatus -ne 'Up') { continue }
        if ($nic.NetworkInterfaceType -eq 'Loopback' -or $nic.NetworkInterfaceType -eq 'Tunnel') { continue }
        $properties = $nic.GetIPProperties()
        $hasGateway = $false
        foreach ($gateway in $properties.GatewayAddresses) {
            if ($gateway.Address.AddressFamily -eq 'InterNetwork' -and $gateway.Address.ToString() -ne '0.0.0.0') { $hasGateway = $true }
        }
        foreach ($unicast in $properties.UnicastAddresses) {
            $address = $unicast.Address
            if ($address.AddressFamily -ne 'InterNetwork') { continue }
            $text = $address.ToString()
            if ($text.StartsWith('127.') -or $text.StartsWith('169.254.')) { continue }
            $result += New-Object psobject -Property @{ Address = $text; InterfaceName = $nic.Name; HasGateway = $hasGateway }
        }
    }
    @($result | Sort-Object -Property @{ Expression = { $_.HasGateway }; Descending = $true }, @{ Expression = { $_.InterfaceName }; Descending = $false })
}

function Set-OgHostClipboard {
    param([string] $Text)
    Set-Clipboard -Value $Text
}

function Start-OgHostServerProcess {
    param([string] $FilePath, [string] $Arguments, [string] $WorkingDirectory)
    Start-Process -FilePath $FilePath -ArgumentList $Arguments -WorkingDirectory $WorkingDirectory -PassThru
}

function Test-OgHostProcessRunning {
    param($Process)
    -not $Process.HasExited
}

function Stop-OgHostServerProcess {
    param($Process)
    & cmd.exe /c "taskkill /PID $($Process.Id) /T /F >nul 2>&1"
    if (-not $Process.HasExited) { Stop-Process -Id $Process.Id -Force }
}

function Start-OgHostClientLaunch {
    param([string] $Target, [string] $WorkingDirectory)
    if ($WorkingDirectory) { Start-Process -FilePath $Target -WorkingDirectory $WorkingDirectory | Out-Null }
    else { Start-Process -FilePath $Target | Out-Null }
}

function New-OgHostLogTail {
    param([string] $Path)
    New-Object psobject -Property @{ Path = $Path; Reader = $null; Pending = '' }
}

function Read-OgHostLogLines {
    param($Tail)
    if ($null -eq $Tail.Reader) {
        if (-not (Test-Path -LiteralPath $Tail.Path -PathType Leaf)) { return @() }
        $share = [System.IO.FileShare]::ReadWrite -bor [System.IO.FileShare]::Delete
        $stream = New-Object System.IO.FileStream($Tail.Path, [System.IO.FileMode]::Open, [System.IO.FileAccess]::Read, $share)
        $Tail.Reader = New-Object System.IO.StreamReader($stream, [System.Text.Encoding]::UTF8, $true)
    }
    $text = $Tail.Pending + $Tail.Reader.ReadToEnd()
    $parts = $text -split "`n"
    $Tail.Pending = $parts[$parts.Count - 1]
    $lines = @()
    for ($i = 0; $i -lt $parts.Count - 1; $i++) { $lines += $parts[$i].TrimEnd("`r") }
    $lines
}

function Close-OgHostLogTail {
    param($Tail)
    if ($Tail -and $Tail.Reader) { $Tail.Reader.Dispose(); $Tail.Reader = $null }
}

function Test-OgHostIPv4 {
    param([string] $Text)
    $parsed = $null
    if (-not [System.Net.IPAddress]::TryParse($Text, [ref]$parsed)) { return $false }
    ($parsed.AddressFamily -eq 'InterNetwork') -and ($Text -match '^\d{1,3}(\.\d{1,3}){3}$')
}

function Test-OgHostSharedAddress {
    param([string] $Address)
    if (-not (Test-OgHostIPv4 $Address)) { return $false }
    $octets = $Address.Split('.')
    ([int]$octets[0] -eq 100) -and ([int]$octets[1] -ge 64) -and ([int]$octets[1] -le 127)
}

function Get-OgHostPublicIp {
    param([string[]] $Services)
    foreach ($service in $Services) {
        try {
            $text = (Invoke-OgHostHttpGet -Uri $service).Trim()
            if (Test-OgHostIPv4 $text) { return $text }
            Write-OgHostLine "  $service did not return an IPv4 address." 'DarkGray'
        }
        catch {
            Write-OgHostLine "  $service did not answer: $($_.Exception.Message)" 'DarkGray'
        }
    }
    $null
}

function ConvertTo-OgHostFriendlyLine {
    param([string] $Line, [System.Text.RegularExpressions.Regex] $Pattern)
    $match = $Pattern.Match($Line)
    if (-not $match.Success) { return $null }
    $players = 0
    if (-not [int]::TryParse($match.Groups['players'].Value, [ref]$players)) { return $null }
    $tested = 0
    $hasTested = $match.Groups['tested'].Success -and [int]::TryParse($match.Groups['tested'].Value, [ref]$tested)
    $verb = $null
    if ($match.Groups['joined'].Success) { $verb = 'joined' }
    elseif ($match.Groups['left'].Success) { $verb = 'left' }
    else { return $null }
    if (-not $hasTested) { return "Player $verb ($players players)" }
    if ($players -gt $tested) {
        if ($verb -eq 'joined') { return "Player joined ($players players - above the tested $tested, expect degraded performance)" }
        return "Player left ($players players - still above the tested $tested)"
    }
    "Player $verb ($players/$tested)"
}

function Format-OgHostBox {
    param([string[]] $Lines)
    $width = 0
    foreach ($line in $Lines) { if ($line.Length -gt $width) { $width = $line.Length } }
    $border = '+' + ('-' * ($width + 4)) + '+'
    $out = @($border)
    foreach ($line in $Lines) { $out += '|  ' + $line.PadRight($width) + '  |' }
    $out += $border
    $out
}

function Read-OgHostSettings {
    param([string] $Root)
    $path = Join-Path $Root 'host_server.settings.psd1'
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Settings file '$path' is missing. Reinstall or verify the server files." }
    $tokens = $null
    $errors = $null
    $ast = [System.Management.Automation.Language.Parser]::ParseFile($path, [ref]$tokens, [ref]$errors)
    if ($errors.Count -gt 0) { throw "Settings file '$path' is damaged: $($errors[0].Message)" }
    $table = $ast.Find({ param($node) $node -is [System.Management.Automation.Language.HashtableAst] }, $false)
    if ($null -eq $table) { throw "Settings file '$path' holds no @{ } table." }
    $table.SafeGetValue()
}

function Resolve-OgHostFirewallProgram {
    param([string] $Program)
    $folder = Split-Path -Parent $Program
    $base = [System.IO.Path]::GetFileNameWithoutExtension($Program)
    $names = @("$base.exe", "$base-Win64-Shipping.exe", "$base-Win64-Test.exe", "$base-Win64-DebugGame.exe")
    foreach ($project in @(Get-ChildItem -LiteralPath $folder -Directory -ErrorAction SilentlyContinue | Sort-Object Name)) {
        foreach ($name in $names) {
            $candidate = Join-Path (Join-Path $project.FullName 'Binaries\Win64') $name
            if (Test-Path -LiteralPath $candidate -PathType Leaf) { return $candidate }
        }
    }
    $Program
}

function Invoke-OgHostFirewallStep {
    param($Settings, [string] $Program)
    $ruleName = "$($Settings.Title) (UDP $($Settings.Port))"
    $exists = $false
    try { $exists = Test-OgHostFirewallRule -RuleName $ruleName -Program $Program -Port $Settings.Port }
    catch { Write-OgHostLine "Firewall: could not read the rules ($($_.Exception.Message)); trying to add one." 'Yellow' }
    if ($exists) {
        Write-OgHostLine "Firewall: rule '$ruleName' already present."
        return 'Exists'
    }
    Write-OgHostLine "Firewall: adding an inbound rule for UDP $($Settings.Port). Windows asks for permission once."
    $arguments = "advfirewall firewall add rule name=`"$ruleName`" dir=in action=allow program=`"$Program`" protocol=UDP localport=$($Settings.Port) profile=any"
    try {
        $code = Invoke-OgHostElevated -FilePath 'netsh.exe' -Arguments $arguments
    }
    catch {
        Write-OgHostLine "Firewall: permission was declined, so no rule was added. Players on other PCs may not reach the server; Windows may ask again when the server starts." 'Yellow'
        return 'Declined'
    }
    if ($code -ne 0) {
        Write-OgHostLine "Firewall: adding the rule failed (netsh exit code $code). Players on other PCs may not reach the server." 'Yellow'
        return 'Failed'
    }
    Write-OgHostLine "Firewall: rule '$ruleName' added."
    'Added'
}

function Invoke-OgHostUpnpStep {
    param($Settings, $Lan)
    $port = [int]$Settings.Port
    $state = New-Object psobject -Property @{ Status = 'Unavailable'; Added = $false; Collection = $null; ExternalIp = $null }
    $internal = @($Lan | Where-Object { $_.HasGateway }) | Select-Object -First 1
    if ($null -eq $internal) {
        Write-OgHostLine "Router: no network adapter with a gateway found, so the router was not asked to open UDP $port." 'Yellow'
        return $state
    }
    $manual = "Forward UDP $port on your router to $($internal.Address) by hand (see your router's 'port forwarding' page)."
    try {
        $collection = Get-OgHostUpnpCollection
    }
    catch {
        $collection = $null
    }
    if ($null -eq $collection) {
        Write-OgHostLine "Router: UPnP unavailable. $manual" 'Yellow'
        return $state
    }
    $state.Collection = $collection
    try {
        $existing = Get-OgHostUpnpMapping -Collection $collection -Port $port
        if ($null -ne $existing -and $existing.InternalClient -ne $internal.Address) {
            $state.Status = 'Taken'
            $state.ExternalIp = [string]$existing.ExternalIPAddress
            Write-OgHostLine "Router: UDP $port is already forwarded to another PC ($($existing.InternalClient)). Stop the server there, or change the forwarding by hand. $manual" 'Yellow'
            return $state
        }
        if ($null -ne $existing) {
            $mapping = $existing
            Write-OgHostLine "Router: reusing the UDP $port forwarding to this PC left from an earlier run."
        }
        else {
            $mapping = Add-OgHostUpnpMapping -Collection $collection -Port $port -InternalClient $internal.Address -Description $Settings.Title
            if ($null -eq $mapping) { throw 'the router returned no mapping' }
            Write-OgHostLine "Router: UDP $port forwarded to this PC ($($internal.Address)) via UPnP. It is removed when this window stops the server."
        }
        $state.Status = 'Mapped'
        $state.Added = $true
        $state.ExternalIp = [string]$mapping.ExternalIPAddress
    }
    catch {
        $state.Status = 'Failed'
        Write-OgHostLine "Router: UPnP port forwarding failed ($($_.Exception.Message)). $manual" 'Yellow'
    }
    $state
}

function Write-OgHostCgnatCheck {
    param([string] $PublicIp, [string] $RouterIp)
    $shared = $false
    if ($RouterIp -and (Test-OgHostSharedAddress $RouterIp)) { $shared = $true }
    if ($PublicIp -and $RouterIp -and $PublicIp -ne $RouterIp) { $shared = $true }
    if (-not $shared) {
        if (-not $RouterIp) { Write-OgHostLine "Could not ask the router for its internet address, so carrier-grade NAT was not checked." 'DarkGray' }
        return $false
    }
    Write-OgHostLine ''
    Write-OgHostLine "WARNING: your router's internet address ($RouterIp) is not this connection's public address ($PublicIp)." 'Red'
    Write-OgHostLine "Your internet provider (or a second router) shares one public address between several connections" 'Red'
    Write-OgHostLine "(carrier-grade NAT). Players on the internet most likely cannot reach this PC. Alternatives:" 'Red'
    Write-OgHostLine "  - host from another internet connection, or ask your provider for a public IPv4 address;" 'Red'
    Write-OgHostLine "  - rent a Windows cloud server near the players and host there;" 'Red'
    Write-OgHostLine "  - use a virtual LAN such as Tailscale or ZeroTier and join with its address;" 'Red'
    Write-OgHostLine "  - players on your own network can still join with the LAN address below." 'Red'
    $true
}

function Get-OgHostJoinAddresses {
    param([string] $Mode, $Settings, $Lan, [string] $InternetIp)
    $port = [int]$Settings.Port
    $entries = @()
    if ($Mode -eq 'Online' -and $InternetIp) {
        $entries += New-Object psobject -Property @{ Kind = 'Internet'; Address = "${InternetIp}:$port"; Note = 'players on the internet' }
    }
    $entries += New-Object psobject -Property @{ Kind = 'This PC'; Address = "127.0.0.1:$port"; Note = 'a game started on this PC' }
    foreach ($nic in @($Lan)) {
        $entries += New-Object psobject -Property @{ Kind = 'LAN'; Address = "$($nic.Address):$port"; Note = "players on your network ($($nic.InterfaceName))" }
    }
    $entries
}

function Select-OgHostJoinAddress {
    param($Entries)
    $internet = @($Entries | Where-Object { $_.Kind -eq 'Internet' }) | Select-Object -First 1
    if ($internet) { return $internet }
    $lan = @($Entries | Where-Object { $_.Kind -eq 'LAN' }) | Select-Object -First 1
    if ($lan) { return $lan }
    @($Entries | Where-Object { $_.Kind -eq 'This PC' }) | Select-Object -First 1
}

function Write-OgHostJoinInfo {
    param([string] $Root, $Entries, $Chosen)
    Write-OgHostLine ''
    foreach ($line in (Format-OgHostBox @("Join address: $($Chosen.Address)", "($($Chosen.Note))"))) { Write-OgHostLine $line 'Green' }
    Write-OgHostLine ''
    Write-OgHostLine 'All addresses:'
    foreach ($entry in $Entries) { Write-OgHostLine ("  {0,-9} {1,-21} {2}" -f $entry.Kind, $entry.Address, $entry.Note) }
    try {
        Set-OgHostClipboard -Text $Chosen.Address
        Write-OgHostLine "The join address $($Chosen.Address) is on the clipboard."
    }
    catch {
        Write-OgHostLine "Could not copy the join address to the clipboard: $($_.Exception.Message)" 'Yellow'
    }
    $text = @("join=$($Chosen.Address)")
    foreach ($entry in $Entries) { $text += "$($entry.Kind)=$($entry.Address)" }
    $path = Join-Path $Root 'join_info.txt'
    try {
        [System.IO.File]::WriteAllText($path, (($text -join "`r`n") + "`r`n"), (New-Object System.Text.UTF8Encoding($false)))
        Write-OgHostLine "Written to $path"
    }
    catch {
        Write-OgHostLine "Could not write '$path': $($_.Exception.Message)" 'Yellow'
    }
}

function Invoke-OgHostClientLaunchStep {
    param($Settings, [string] $Root)
    $launch = [string]$Settings.ClientLaunch
    if (-not $launch) {
        if ($Settings.ClientLaunchSkipReason) { Write-OgHostLine "Not starting the game automatically: $($Settings.ClientLaunchSkipReason). Start it yourself." 'Yellow' }
        else { Write-OgHostLine 'Start the game yourself to play on this PC.' }
    }
    else {
        $answer = [string](Read-OgHostAnswer -Prompt 'Start the game on this PC now? [Y/n]')
        if ($answer.Trim() -match '^(n|no)$') {
            Write-OgHostLine 'OK, start the game yourself when you want to play on this PC.'
        }
        elseif ($launch -match '^[A-Za-z][A-Za-z0-9+.-]+:') {
            try { Start-OgHostClientLaunch -Target $launch; Write-OgHostLine "Starting the game ($launch)." }
            catch { Write-OgHostLine "Could not start the game ($launch): $($_.Exception.Message). Start it yourself." 'Yellow' }
        }
        else {
            $path = [System.IO.Path]::GetFullPath((Join-Path $Root $launch))
            if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
                Write-OgHostLine "The game was not found at '$path'. Start it yourself." 'Yellow'
            }
            else {
                try { Start-OgHostClientLaunch -Target $path -WorkingDirectory (Split-Path -Parent $path); Write-OgHostLine "Starting the game ($path)." }
                catch { Write-OgHostLine "Could not start the game ($path): $($_.Exception.Message). Start it yourself." 'Yellow' }
            }
        }
    }
    Write-OgHostLine "In the game, pick 'This PC' (127.0.0.1:$($Settings.Port)) and press Join." 'Cyan'
    if ($Settings.LocalHint) { Write-OgHostLine $Settings.LocalHint 'Cyan' }
}

function Invoke-OgHostCleanup {
    param($Session)
    if ($Session.Tail) { Close-OgHostLogTail $Session.Tail }
    if ($Session.Server) {
        $running = $false
        try { $running = Test-OgHostProcessRunning -Process $Session.Server } catch { $running = $false }
        if ($running) {
            Write-OgHostLine 'Stopping the server.'
            try { Stop-OgHostServerProcess -Process $Session.Server } catch { Write-OgHostLine "Could not stop the server: $($_.Exception.Message)" 'Yellow' }
        }
    }
    if ($Session.Upnp -and $Session.Upnp.Added) {
        try {
            Remove-OgHostUpnpMapping -Collection $Session.Upnp.Collection -Port ([int]$Session.Settings.Port)
            Write-OgHostLine "Router: UDP $($Session.Settings.Port) forwarding removed."
        }
        catch {
            Write-OgHostLine "Router: could not remove the UDP $($Session.Settings.Port) forwarding ($($_.Exception.Message)). Remove it in the router, or run this script again and stop it with Ctrl+C." 'Yellow'
        }
    }
}

function Invoke-OgHostSession {
    param([string] $Mode, [string] $Root)
    $settings = Read-OgHostSettings -Root $Root
    $session = New-Object psobject -Property @{ Settings = $settings; Upnp = $null; Server = $null; Tail = $null }
    $program = [System.IO.Path]::GetFullPath((Join-Path $Root $settings.ServerExecutable))
    if (-not (Test-Path -LiteralPath $program -PathType Leaf)) { throw "The server program '$program' is missing. Reinstall or verify the server files." }
    $joinPattern = New-Object System.Text.RegularExpressions.Regex($settings.JoinLinePattern)
    $readyPattern = $null
    if ($settings.ReadyLinePattern) { $readyPattern = New-Object System.Text.RegularExpressions.Regex($settings.ReadyLinePattern) }

    Write-OgHostLine "=== $($settings.Title) - $Mode playtest ===" 'Cyan'
    try {
        Invoke-OgHostFirewallStep -Settings $settings -Program (Resolve-OgHostFirewallProgram -Program $program) | Out-Null

        $lan = @(Get-OgHostLanAddresses)
        $internetIp = $null
        if ($Mode -eq 'Online') {
            $session.Upnp = Invoke-OgHostUpnpStep -Settings $settings -Lan $lan
            Write-OgHostLine 'Looking up the public internet address...'
            $publicIp = Get-OgHostPublicIp -Services $settings.PublicIpServices
            $routerIp = $session.Upnp.ExternalIp
            if (-not $publicIp) { Write-OgHostLine 'Could not look up the public internet address (no internet, or the lookup services are down).' 'Yellow' }
            Write-OgHostCgnatCheck -PublicIp $publicIp -RouterIp $routerIp | Out-Null
            if ($publicIp) { $internetIp = $publicIp } elseif (Test-OgHostIPv4 $routerIp) { $internetIp = $routerIp }
        }
        $entries = @(Get-OgHostJoinAddresses -Mode $Mode -Settings $settings -Lan $lan -InternetIp $internetIp)
        Write-OgHostJoinInfo -Root $Root -Entries $entries -Chosen (Select-OgHostJoinAddress $entries)

        $logDir = Join-Path $Root 'HostLogs'
        if (-not (Test-Path -LiteralPath $logDir -PathType Container)) { New-Item -ItemType Directory -Path $logDir | Out-Null }
        $logPath = Join-Path $logDir ("server-{0}.log" -f (Get-Date -Format 'yyyyMMdd-HHmmss'))
        $arguments = ("{0} -port={1} -log -abslog=`"{2}`"" -f $settings.ServerArguments, $settings.Port, $logPath).Trim()
        Write-OgHostLine ''
        Write-OgHostLine "Starting the server: $program $arguments"
        $session.Tail = New-OgHostLogTail -Path $logPath
        $session.Server = Start-OgHostServerProcess -FilePath $program -Arguments $arguments -WorkingDirectory (Split-Path -Parent $program)
        if ($session.Upnp -and $session.Upnp.Added) {
            Write-OgHostLine 'Press Ctrl+C here to stop the server. Closing this window instead leaves the router forwarding in place until the next run.'
        }
        else {
            Write-OgHostLine 'Press Ctrl+C here to stop the server.'
        }

        $ready = $null -eq $readyPattern
        $offered = $false
        while ($true) {
            $running = Test-OgHostProcessRunning -Process $session.Server
            foreach ($line in @(Read-OgHostLogLines -Tail $session.Tail)) {
                if (-not $ready -and $readyPattern.IsMatch($line)) {
                    $ready = $true
                    Write-OgHostLine "Server is ready on UDP $($settings.Port)." 'Green'
                }
                $friendly = ConvertTo-OgHostFriendlyLine -Line $line -Pattern $joinPattern
                if ($friendly) { Write-OgHostLine ("[{0}] {1}" -f (Get-Date -Format 'HH:mm:ss'), $friendly) 'Green' }
            }
            if (-not $running) { break }
            if ($ready -and -not $offered) {
                $offered = $true
                Invoke-OgHostClientLaunchStep -Settings $settings -Root $Root
            }
            Wait-OgHostTick
        }
        Write-OgHostLine "The server stopped (exit code $($session.Server.ExitCode)). Its log: $logPath"
    }
    finally {
        Invoke-OgHostCleanup -Session $session
    }
}

function Invoke-OgHostMain {
    param([string] $Mode, [string] $Root)
    $ErrorActionPreference = 'Stop'
    try {
        $null = Invoke-OgHostSession -Mode $Mode -Root $Root
        0
    }
    catch {
        Write-OgHostLine "ERROR: $($_.Exception.Message)" 'Red'
        1
    }
}

if ($MyInvocation.InvocationName -ne '.') {
    $exitCode = Invoke-OgHostMain -Mode $Mode -Root $PSScriptRoot
    exit $exitCode
}
